telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://<...>.ngrok.io"
  bot-name: "<что-то вроде @NameOfYourBot>"
  bot-token: "<токен бота - цифры, двоеточие и белиберда:)>"
spring:
  redis:
    database: 0
    host: "<...>.compute-1.amazonaws.com"
    port: "<как правило, 5 цифр, если деплоим на Heroku>"
    password: "<очень длинный пароль:)>"
    ssl: true
server:
  port: "80"